"""baseline esquema completo

Revision ID: 76ffafb10bef
Revises: 
Create Date: 2026-06-30 13:59:37.463976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '76ffafb10bef'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # embedding de media: VECTOR(512) en Postgres con pgvector, Text en SQLite
    if op.get_bind().dialect.name == 'postgresql':
        # La extensión pgvector debe existir antes de crear columnas VECTOR
        op.execute("CREATE EXTENSION IF NOT EXISTS vector")
        from pgvector.sqlalchemy import Vector
        embedding_type = Vector(512)
    else:
        embedding_type = sa.Text()
    op.create_table('api_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('client_ip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('error_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_metrics_method'), 'api_metrics', ['method'], unique=False)
    op.create_index(op.f('ix_api_metrics_path'), 'api_metrics', ['path'], unique=False)
    op.create_index(op.f('ix_api_metrics_status_code'), 'api_metrics', ['status_code'], unique=False)
    op.create_index(op.f('ix_api_metrics_timestamp'), 'api_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_api_metrics_user_id'), 'api_metrics', ['user_id'], unique=False)
    op.create_table('cors_origins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('origin', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cors_origins_origin'), 'cors_origins', ['origin'], unique=True)
    op.create_table('media',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('file_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('alt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('embedding', embedding_type, nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('storage_backend', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_deleted_at'), 'media', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_media_file_type'), 'media', ['file_type'], unique=False)
    op.create_index(op.f('ix_media_filename'), 'media', ['filename'], unique=False)
    op.create_index(op.f('ix_media_organization_id'), 'media', ['organization_id'], unique=False)
    op.create_index(op.f('ix_media_storage_path'), 'media', ['storage_path'], unique=True)
    op.create_index(op.f('ix_media_user_id'), 'media', ['user_id'], unique=False)
    op.create_table('organizations',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_deleted_at'), 'organizations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_organizations_name'), 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_name'), 'permissions', ['name'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superadmin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_provider'), 'users', ['provider'], unique=False)
    op.create_index(op.f('ix_users_provider_user_id'), 'users', ['provider_user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_prefix', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('scopes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_name'), 'api_keys', ['name'], unique=False)
    op.create_index(op.f('ix_api_keys_organization_id'), 'api_keys', ['organization_id'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('aseguradora',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contactos', sa.JSON(), nullable=True),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'nombre', name='uq_aseguradora_nombre')
    )
    op.create_index(op.f('ix_aseguradora_deleted_at'), 'aseguradora', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_aseguradora_nombre'), 'aseguradora', ['nombre'], unique=False)
    op.create_index(op.f('ix_aseguradora_organization_id'), 'aseguradora', ['organization_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('organization_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('resource_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cliente',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('numero_cliente', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('documento_identidad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cliente_apellido'), 'cliente', ['apellido'], unique=False)
    op.create_index(op.f('ix_cliente_deleted_at'), 'cliente', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_cliente_documento_identidad'), 'cliente', ['documento_identidad'], unique=False)
    op.create_index(op.f('ix_cliente_nombre'), 'cliente', ['nombre'], unique=False)
    op.create_index(op.f('ix_cliente_organization_id'), 'cliente', ['organization_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('invited_by', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invitations_token_hash'), 'invitations', ['token_hash'], unique=True)
    op.create_table('memberships',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_org')
    )
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_agent', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('gateway', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gateway_customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gateway_subscription_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('plan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscriptions_organization_id'), 'subscriptions', ['organization_id'], unique=True)
    op.create_table('taller',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('departamento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ciudad', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('telefono2', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('especialidad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('marcas_atendidas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('horario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_taller_deleted_at'), 'taller', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_taller_departamento'), 'taller', ['departamento'], unique=False)
    op.create_index(op.f('ix_taller_nombre'), 'taller', ['nombre'], unique=False)
    op.create_index(op.f('ix_taller_organization_id'), 'taller', ['organization_id'], unique=False)
    op.create_table('tasks',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('task_data', sa.JSON(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_deleted_at'), 'tasks', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_index(op.f('ix_tasks_task_type'), 'tasks', ['task_type'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('aseguradora_taller',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('aseguradora_id', sa.Integer(), nullable=False),
    sa.Column('taller_id', sa.Integer(), nullable=False),
    sa.Column('zona', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prioridad', sa.Integer(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=True),
    sa.Column('vigente_hasta', sa.Date(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aseguradora_id'], ['aseguradora.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['taller_id'], ['taller.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('aseguradora_id', 'taller_id', name='uq_aseg_taller')
    )
    op.create_index(op.f('ix_aseguradora_taller_aseguradora_id'), 'aseguradora_taller', ['aseguradora_id'], unique=False)
    op.create_index(op.f('ix_aseguradora_taller_organization_id'), 'aseguradora_taller', ['organization_id'], unique=False)
    op.create_index(op.f('ix_aseguradora_taller_taller_id'), 'aseguradora_taller', ['taller_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('gateway', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gateway_payment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_gateway_payment_id'), 'payments', ['gateway_payment_id'], unique=False)
    op.create_index(op.f('ix_payments_organization_id'), 'payments', ['organization_id'], unique=False)
    op.create_index(op.f('ix_payments_subscription_id'), 'payments', ['subscription_id'], unique=False)
    op.create_table('vehiculo',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('marca', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.Column('matricula', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numero_motor', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('numero_chasis', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'matricula', name='uq_vehiculo_matricula')
    )
    op.create_index(op.f('ix_vehiculo_cliente_id'), 'vehiculo', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_vehiculo_deleted_at'), 'vehiculo', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_vehiculo_matricula'), 'vehiculo', ['matricula'], unique=False)
    op.create_index(op.f('ix_vehiculo_organization_id'), 'vehiculo', ['organization_id'], unique=False)
    op.create_table('poliza',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('vehiculo_id', sa.Integer(), nullable=True),
    sa.Column('aseguradora_id', sa.Integer(), nullable=False),
    sa.Column('corredor_id', sa.Integer(), nullable=True),
    sa.Column('numero_poliza', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_seguro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('vigente_desde', sa.Date(), nullable=False),
    sa.Column('vigente_hasta', sa.Date(), nullable=False),
    sa.Column('prima_total', sa.Float(), nullable=True),
    sa.Column('moneda', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('total_cuotas', sa.Integer(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aseguradora_id'], ['aseguradora.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['corredor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['vehiculo_id'], ['vehiculo.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'numero_poliza', name='uq_poliza_numero')
    )
    op.create_index(op.f('ix_poliza_aseguradora_id'), 'poliza', ['aseguradora_id'], unique=False)
    op.create_index(op.f('ix_poliza_cliente_id'), 'poliza', ['cliente_id'], unique=False)
    op.create_index(op.f('ix_poliza_deleted_at'), 'poliza', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_poliza_estado'), 'poliza', ['estado'], unique=False)
    op.create_index(op.f('ix_poliza_numero_poliza'), 'poliza', ['numero_poliza'], unique=False)
    op.create_index(op.f('ix_poliza_organization_id'), 'poliza', ['organization_id'], unique=False)
    op.create_table('cuota',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('poliza_id', sa.Integer(), nullable=False),
    sa.Column('numero_cuota', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Float(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=False),
    sa.Column('fecha_pago', sa.Date(), nullable=True),
    sa.Column('pagada', sa.Boolean(), nullable=False),
    sa.Column('metodo_pago', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['poliza_id'], ['poliza.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('poliza_id', 'numero_cuota', name='uq_cuota_poliza_numero')
    )
    op.create_index(op.f('ix_cuota_fecha_vencimiento'), 'cuota', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_cuota_organization_id'), 'cuota', ['organization_id'], unique=False)
    op.create_index(op.f('ix_cuota_poliza_id'), 'cuota', ['poliza_id'], unique=False)
    op.create_table('siniestro',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('poliza_id', sa.Integer(), nullable=False),
    sa.Column('aseguradora_id', sa.Integer(), nullable=False),
    sa.Column('numero_siniestro', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_ocurrencia', sa.Date(), nullable=True),
    sa.Column('fecha_denuncia', sa.Date(), nullable=True),
    sa.Column('tipo_dano', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('monto_reclamado', sa.Float(), nullable=True),
    sa.Column('monto_liquidado', sa.Float(), nullable=True),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aseguradora_id'], ['aseguradora.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['poliza_id'], ['poliza.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'numero_siniestro', name='uq_siniestro_numero')
    )
    op.create_index(op.f('ix_siniestro_aseguradora_id'), 'siniestro', ['aseguradora_id'], unique=False)
    op.create_index(op.f('ix_siniestro_deleted_at'), 'siniestro', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_siniestro_estado'), 'siniestro', ['estado'], unique=False)
    op.create_index(op.f('ix_siniestro_numero_siniestro'), 'siniestro', ['numero_siniestro'], unique=False)
    op.create_index(op.f('ix_siniestro_organization_id'), 'siniestro', ['organization_id'], unique=False)
    op.create_index(op.f('ix_siniestro_poliza_id'), 'siniestro', ['poliza_id'], unique=False)
    op.create_table('mensaje',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('asunto', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('contenido', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('fecha_leido', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('poliza_id', sa.Integer(), nullable=True),
    sa.Column('siniestro_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['destinatario_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['poliza_id'], ['poliza.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['siniestro_id'], ['siniestro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mensaje_destinatario_id'), 'mensaje', ['destinatario_id'], unique=False)
    op.create_index(op.f('ix_mensaje_organization_id'), 'mensaje', ['organization_id'], unique=False)
    op.create_table('siniestro_documento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('siniestro_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('recibido', sa.Boolean(), nullable=False),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('archivo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notas', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['siniestro_id'], ['siniestro.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('siniestro_id', 'tipo_documento', name='uq_sinDoc_tipo')
    )
    op.create_index(op.f('ix_siniestro_documento_organization_id'), 'siniestro_documento', ['organization_id'], unique=False)
    op.create_index(op.f('ix_siniestro_documento_siniestro_id'), 'siniestro_documento', ['siniestro_id'], unique=False)
    op.create_table('tarea',
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('creado_por', sa.Integer(), nullable=False),
    sa.Column('asignado_a', sa.Integer(), nullable=True),
    sa.Column('titulo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('prioridad', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fecha_vencimiento', sa.Date(), nullable=True),
    sa.Column('fecha_completada', sa.DateTime(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('poliza_id', sa.Integer(), nullable=True),
    sa.Column('siniestro_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asignado_a'], ['users.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['creado_por'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['poliza_id'], ['poliza.id'], ),
    sa.ForeignKeyConstraint(['siniestro_id'], ['siniestro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tarea_asignado_a'), 'tarea', ['asignado_a'], unique=False)
    op.create_index(op.f('ix_tarea_deleted_at'), 'tarea', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_tarea_estado'), 'tarea', ['estado'], unique=False)
    op.create_index(op.f('ix_tarea_fecha_vencimiento'), 'tarea', ['fecha_vencimiento'], unique=False)
    op.create_index(op.f('ix_tarea_organization_id'), 'tarea', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tarea_organization_id'), table_name='tarea')
    op.drop_index(op.f('ix_tarea_fecha_vencimiento'), table_name='tarea')
    op.drop_index(op.f('ix_tarea_estado'), table_name='tarea')
    op.drop_index(op.f('ix_tarea_deleted_at'), table_name='tarea')
    op.drop_index(op.f('ix_tarea_asignado_a'), table_name='tarea')
    op.drop_table('tarea')
    op.drop_index(op.f('ix_siniestro_documento_siniestro_id'), table_name='siniestro_documento')
    op.drop_index(op.f('ix_siniestro_documento_organization_id'), table_name='siniestro_documento')
    op.drop_table('siniestro_documento')
    op.drop_index(op.f('ix_mensaje_organization_id'), table_name='mensaje')
    op.drop_index(op.f('ix_mensaje_destinatario_id'), table_name='mensaje')
    op.drop_table('mensaje')
    op.drop_index(op.f('ix_siniestro_poliza_id'), table_name='siniestro')
    op.drop_index(op.f('ix_siniestro_organization_id'), table_name='siniestro')
    op.drop_index(op.f('ix_siniestro_numero_siniestro'), table_name='siniestro')
    op.drop_index(op.f('ix_siniestro_estado'), table_name='siniestro')
    op.drop_index(op.f('ix_siniestro_deleted_at'), table_name='siniestro')
    op.drop_index(op.f('ix_siniestro_aseguradora_id'), table_name='siniestro')
    op.drop_table('siniestro')
    op.drop_index(op.f('ix_cuota_poliza_id'), table_name='cuota')
    op.drop_index(op.f('ix_cuota_organization_id'), table_name='cuota')
    op.drop_index(op.f('ix_cuota_fecha_vencimiento'), table_name='cuota')
    op.drop_table('cuota')
    op.drop_index(op.f('ix_poliza_organization_id'), table_name='poliza')
    op.drop_index(op.f('ix_poliza_numero_poliza'), table_name='poliza')
    op.drop_index(op.f('ix_poliza_estado'), table_name='poliza')
    op.drop_index(op.f('ix_poliza_deleted_at'), table_name='poliza')
    op.drop_index(op.f('ix_poliza_cliente_id'), table_name='poliza')
    op.drop_index(op.f('ix_poliza_aseguradora_id'), table_name='poliza')
    op.drop_table('poliza')
    op.drop_index(op.f('ix_vehiculo_organization_id'), table_name='vehiculo')
    op.drop_index(op.f('ix_vehiculo_matricula'), table_name='vehiculo')
    op.drop_index(op.f('ix_vehiculo_deleted_at'), table_name='vehiculo')
    op.drop_index(op.f('ix_vehiculo_cliente_id'), table_name='vehiculo')
    op.drop_table('vehiculo')
    op.drop_index(op.f('ix_payments_subscription_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_organization_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_gateway_payment_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_aseguradora_taller_taller_id'), table_name='aseguradora_taller')
    op.drop_index(op.f('ix_aseguradora_taller_organization_id'), table_name='aseguradora_taller')
    op.drop_index(op.f('ix_aseguradora_taller_aseguradora_id'), table_name='aseguradora_taller')
    op.drop_table('aseguradora_taller')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_type'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_deleted_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_taller_organization_id'), table_name='taller')
    op.drop_index(op.f('ix_taller_nombre'), table_name='taller')
    op.drop_index(op.f('ix_taller_departamento'), table_name='taller')
    op.drop_index(op.f('ix_taller_deleted_at'), table_name='taller')
    op.drop_table('taller')
    op.drop_index(op.f('ix_subscriptions_organization_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_invitations_token_hash'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    op.drop_index(op.f('ix_cliente_organization_id'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_nombre'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_documento_identidad'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_deleted_at'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_apellido'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_aseguradora_organization_id'), table_name='aseguradora')
    op.drop_index(op.f('ix_aseguradora_nombre'), table_name='aseguradora')
    op.drop_index(op.f('ix_aseguradora_deleted_at'), table_name='aseguradora')
    op.drop_table('aseguradora')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_organization_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_name'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_users_provider_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_provider'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_permissions_name'), table_name='permissions')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_name'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_deleted_at'), table_name='organizations')
    op.drop_table('organizations')
    op.drop_index(op.f('ix_media_user_id'), table_name='media')
    op.drop_index(op.f('ix_media_storage_path'), table_name='media')
    op.drop_index(op.f('ix_media_organization_id'), table_name='media')
    op.drop_index(op.f('ix_media_filename'), table_name='media')
    op.drop_index(op.f('ix_media_file_type'), table_name='media')
    op.drop_index(op.f('ix_media_deleted_at'), table_name='media')
    op.drop_table('media')
    op.drop_index(op.f('ix_cors_origins_origin'), table_name='cors_origins')
    op.drop_table('cors_origins')
    op.drop_index(op.f('ix_api_metrics_user_id'), table_name='api_metrics')
    op.drop_index(op.f('ix_api_metrics_timestamp'), table_name='api_metrics')
    op.drop_index(op.f('ix_api_metrics_status_code'), table_name='api_metrics')
    op.drop_index(op.f('ix_api_metrics_path'), table_name='api_metrics')
    op.drop_index(op.f('ix_api_metrics_method'), table_name='api_metrics')
    op.drop_table('api_metrics')
    # ### end Alembic commands ###
